/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ControleIdRouteImport } from './routes/controle.$id'
import { Route as HistoricoIndexRouteImport } from './routes/historico.index'
import { Route as HistoricoSessionIdRouteImport } from './routes/historico.$sessionId'
import { Route as RoteirosIndexRouteImport } from './routes/roteiros.index'
import { Route as RoteirosIdRouteImport } from './routes/roteiros.$id'
import { Route as RoteirosCriarRouteImport } from './routes/roteiros.criar'
import { Route as TreinoIdRouteImport } from './routes/treino.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleIdRoute = ControleIdRouteImport.update({
  id: '/controle/$id',
  path: '/controle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/historico/',
  path: '/historico/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoSessionIdRoute = HistoricoSessionIdRouteImport.update({
  id: '/historico/$sessionId',
  path: '/historico/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIndexRoute = RoteirosIndexRouteImport.update({
  id: '/roteiros/',
  path: '/roteiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIdRoute = RoteirosIdRouteImport.update({
  id: '/roteiros/$id',
  path: '/roteiros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosCriarRoute = RoteirosCriarRouteImport.update({
  id: '/roteiros/criar',
  path: '/roteiros/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIdRoute = TreinoIdRouteImport.update({
  id: '/treino/$id',
  path: '/treino/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/controle/$id': typeof ControleIdRoute
  '/historico/$sessionId': typeof HistoricoSessionIdRoute
  '/roteiros/$id': typeof RoteirosIdRoute
  '/roteiros/criar': typeof RoteirosCriarRoute
  '/treino/$id': typeof TreinoIdRoute
  '/historico/': typeof HistoricoIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/controle/$id': typeof ControleIdRoute
  '/historico/$sessionId': typeof HistoricoSessionIdRoute
  '/roteiros/$id': typeof RoteirosIdRoute
  '/roteiros/criar': typeof RoteirosCriarRoute
  '/treino/$id': typeof TreinoIdRoute
  '/historico': typeof HistoricoIndexRoute
  '/roteiros': typeof RoteirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/controle/$id': typeof ControleIdRoute
  '/historico/$sessionId': typeof HistoricoSessionIdRoute
  '/roteiros/$id': typeof RoteirosIdRoute
  '/roteiros/criar': typeof RoteirosCriarRoute
  '/treino/$id': typeof TreinoIdRoute
  '/historico/': typeof HistoricoIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/configuracoes'
    | '/estatisticas'
    | '/login'
    | '/usuarios'
    | '/controle/$id'
    | '/historico/$sessionId'
    | '/roteiros/$id'
    | '/roteiros/criar'
    | '/treino/$id'
    | '/historico/'
    | '/roteiros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/configuracoes'
    | '/estatisticas'
    | '/login'
    | '/usuarios'
    | '/controle/$id'
    | '/historico/$sessionId'
    | '/roteiros/$id'
    | '/roteiros/criar'
    | '/treino/$id'
    | '/historico'
    | '/roteiros'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/configuracoes'
    | '/estatisticas'
    | '/login'
    | '/usuarios'
    | '/controle/$id'
    | '/historico/$sessionId'
    | '/roteiros/$id'
    | '/roteiros/criar'
    | '/treino/$id'
    | '/historico/'
    | '/roteiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstatisticasRoute: typeof EstatisticasRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
  ControleIdRoute: typeof ControleIdRoute
  HistoricoSessionIdRoute: typeof HistoricoSessionIdRoute
  RoteirosIdRoute: typeof RoteirosIdRoute
  RoteirosCriarRoute: typeof RoteirosCriarRoute
  TreinoIdRoute: typeof TreinoIdRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
  RoteirosIndexRoute: typeof RoteirosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle/$id': {
      id: '/controle/$id'
      path: '/controle/$id'
      fullPath: '/controle/$id'
      preLoaderRoute: typeof ControleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$sessionId': {
      id: '/historico/$sessionId'
      path: '/historico/$sessionId'
      fullPath: '/historico/$sessionId'
      preLoaderRoute: typeof HistoricoSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/': {
      id: '/roteiros/'
      path: '/roteiros'
      fullPath: '/roteiros/'
      preLoaderRoute: typeof RoteirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/$id': {
      id: '/roteiros/$id'
      path: '/roteiros/$id'
      fullPath: '/roteiros/$id'
      preLoaderRoute: typeof RoteirosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/criar': {
      id: '/roteiros/criar'
      path: '/roteiros/criar'
      fullPath: '/roteiros/criar'
      preLoaderRoute: typeof RoteirosCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/$id': {
      id: '/treino/$id'
      path: '/treino/$id'
      fullPath: '/treino/$id'
      preLoaderRoute: typeof TreinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstatisticasRoute: EstatisticasRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
  ControleIdRoute: ControleIdRoute,
  HistoricoSessionIdRoute: HistoricoSessionIdRoute,
  RoteirosIdRoute: RoteirosIdRoute,
  RoteirosCriarRoute: RoteirosCriarRoute,
  TreinoIdRoute: TreinoIdRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
  RoteirosIndexRoute: RoteirosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
